### ISSUE TITLE
Commands Are Not Working?

### ISSUE THREAD

**Issue by Handeril** [CaliforniaDemise/VoidIslandControl#3]
![2024-12-13_20 30 06](https://github.com/user-attachments/assets/e8da7697-7c81-49c7-845d-e1a1b09956e2)

When I run commands, either nothing happens, or I get this error.

Not sure what's going on.

Thank you for your time, in advance.

**Comment by Handeril** [comment]
[20:29:52] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: island leave
java.lang.NullPointerException: null
	at com.bartz24.voidislandcontrol.PlatformCommand.leavePlatform(PlatformCommand.java:494) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.execute(PlatformCommand.java:123) ~[PlatformCommand.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.execute(CommandOverride.java:83) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[20:29:52] [Client thread/INFO] [de.keksuccino.biggerchathistory.CustomChatGui]: [CHAT] An unknown error occurred while attempting to perform this command
[20:30:01] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: island reset
java.lang.NullPointerException: null
	at com.bartz24.voidislandcontrol.PlatformCommand.leavePlatform(PlatformCommand.java:494) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.reset(PlatformCommand.java:267) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.execute(PlatformCommand.java:133) ~[PlatformCommand.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.execute(CommandOverride.java:83) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[20:30:01] [Client thread/INFO] [de.keksuccino.biggerchathistory.CustomChatGui]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by Handeril** [comment]
Another issue also came up when the commands finally worked. When the island generated, several mods tried to generate structures on top of it.

Examples are Unseen's Nether Backport, and Project Vibrant Jouneys and it's fallen trees.

All of these attempts to generate structures led to the Internal Server crashing.

Is there a way to protect islands from having structures generated over them?

**Comment by Handeril** [comment]
![2024-12-13_23 36 06](https://github.com/user-attachments/assets/73d66ca3-e11b-4321-ae2f-9ff98bc2365d)
![2024-12-13_23 36 52](https://github.com/user-attachments/assets/bce2504e-0453-4cde-821f-d6899ed0c9b2)
[mc_threaddump24.txt](https://github.com/user-attachments/files/18134997/mc_threaddump24.txt)

The thread dump shows what the internal server got stuck in an infinite loop on.
